let
//Imports credit scores and converts seperates out the columns
    Source = Csv.Document(File.Contents("O:\IFRS9_New\Credit Scores\IFRSBorrowers.txt.153748.fullfill"),38,{0,9,36,52,68,70,78,108,128,130,140,150,180,200,202,212,222,230,246,262,286,287,295,305,315,325,335,345,355,356,357,358,366,369,372,375,378,381},null,1252),
    #"Renamed Columns" = Table.RenameColumns(Source,
        {{"Column1", "SIN"}, 
        {"Column2", "Last Name"}, 
        {"Column3", "First Name"}, 
        {"Column4", "Middle Name"}, 
        {"Column5", "Name Suffix"}, 
        {"Column6", "Date of Birth"}, 
        {"Column7", "Civic Address"}, 
        {"Column8", "City"}, 
        {"Column9", "Province"}, 
        {"Column10", "Postal Code"}, 
        {"Column11", "Telephone #"}, 
        {"Column12", "Previous Civic Address"}, 
        {"Column13", "Previous City"}, 
        {"Column14", "Previous Province"}, 
        {"Column15", "Previous Postal Code"}, 
        {"Column16", "Previous Telephone #"}, 
        {"Column17", "Application/Filter Date"}, 
        {"Column18", "Account #1"}, 
        {"Column19", "Account #2"}, 
        {"Column20", "Unique Record ID"}, 
        {"Column21", "Hit/Nohit/EditReject Flag"}, 
        {"Column22", "Run Date"}, 
        {"Column23", "#HK# Home telephone number"}, 
        {"Column24", "#HK# Cell telephone number"}, 
        {"Column25", "#HK# Hine Alternate telephone number"}, 
        {"Column26", "#HK# Work telephone number"}, 
        {"Column27", "#HK# Work Cell telephone number"}, 
        {"Column28", "#HK# Work Alternate telephone number"}, 
        {"Column29", "#HK# Potential flag"}, 
        {"Column30", "#HK# Confirmed flag"}, 
        {"Column31", "#HK# Compromise Flag"}, 
        {"Column32", "#HK# Date of most recently reported Alert"}, 
        {"Column33", "Fico Risk Score 8 - Score"},
        {"Column34", "Fico Risk Score 8 - Factor code 1"}, 
        {"Column35", "Fico Risk Score 8 - Factor code 2"}, 
        {"Column36", "Fico Risk Score 8 - Factor code 3"}, 
        {"Column37", "Factor code 4"}, 
        {"Column38", "Fico Risk Score 8 - Exclusion code"}}),
    #"Added Source" = Table.AddColumn(#"Renamed Columns", "Source", each if Text.Contains([Unique Record ID], "BCU") then
        "BCU"
    else "RCCU"),
    #"Removed source from unique record" = Table.TransformColumns(#"Added Source",
        {"Unique Record ID", each Text.Remove(_, {"B","C","U","R"})}),
    #"Changed Type" = Table.TransformColumnTypes(#"Removed source from unique record",{{"Source", type text}, {"Unique Record ID", Int64.Type}, {"Run Date", Int64.Type}}),
    #"Removed Duplicates" = Table.Distinct(#"Changed Type", {"SIN", "Last Name", "First Name", "Middle Name", "Name Suffix", "Date of Birth", "Civic Address", "City", "Province", "Postal Code", "Previous Civic Address", "Previous City", "Previous Province", "Previous Postal Code", "Previous Telephone #", "Application/Filter Date", "Account #1", "Account #2", "Unique Record ID", "Hit/Nohit/EditReject Flag", "Run Date", "#HK# Home telephone number", "#HK# Cell telephone number", "#HK# Hine Alternate telephone number", "#HK# Work telephone number", "#HK# Work Cell telephone number", "#HK# Work Alternate telephone number", "#HK# Potential flag", "#HK# Confirmed flag", "#HK# Compromise Flag", "#HK# Date of most recently reported Alert", "Fico Risk Score 8 - Score", "Fico Risk Score 8 - Factor code 1", "Fico Risk Score 8 - Factor code 2", "Fico Risk Score 8 - Factor code 3", "Factor code 4", "Fico Risk Score 8 - Exclusion code", "Source"})
in
    #"Removed Duplicates"